package abc.parser;

public enum MusicGrammar {
        ROOT, 
        MUSIC,
        VOICE,
        LINE,
        ELEMENT,
        NOTEELEMENT,
        NOTE,
        NOTEORREST,
        PITCH,
        OCTAVE,
        NOTELENGTH,
        NOTELENGTHSTRICT,
        ACCIDENTAL,
        BASENOTE,
        REST,
        TUPLETELEMENT,
        TUPLETSPEC,
        MULTINOTE,
        BARLINE,
        NTHREPEAT,
        MIDTUNEFIELD,
        COMMENT,
        EOL,
        TEXT,
        DIGIT,
        NUMERATOR,
        DENOMINATOR,
        DIVISION,
        ALPHABET,
        NEWLINE,
        WHITESPACE
}
